### ISSUE TITLE
Unable to configure XBOX wired controller digital pad

### ISSUE THREAD

**Issue by Fulviuus** [pokebyte/CocoaMSX#12]
I am trying to configure an xbox 360 wired gamepad, but I am unable to do so.
The A + B buttons can be assigned, but the UP - DOWN - LEFT - RIGHT assignments only respond to input coming from the left analog stick (not the digital directional pad) and even then, it seems way too sensitive, as soon as I move the stick all input are assigned immediately.

**Comment by pokebyte** [comment]
It took forever (sorry!), but it's finally fixed.

**Comment by Fulviuus** [comment]
Hi, from what I see this still does not fix the issue, I still cannot assign left-right-up-down to the digital pad, and I can only move characters with the analog stick.
Am I doing something wrong?

**Comment by pokebyte** [comment]
It should fix the sensitivity issue, in that the left analog stick should now be usable. The joystick configuration screen was originally only intended to calibrate the directional controls (determine H/V bounds on the analog stick) and change mapping for buttons 1 and 2. Since calibration is now unnecessary (there's a way to query the OS for the information), I disabled the calibration options completely.

Adding support for the D-pad and the second analog stick 2 is a bit more involved; however, feel free to create an additional issue, and I'll do my best to address it for the 1.5 release.

**Comment by pokebyte** [comment]
I went ahead and created a new ticket (#35) myself. I'll do my best to address this in the next release - but I can't promise that at the moment.
